parameters:
  - name: moduleName
    type: string
  - name: dependsOn
    type: string
    default: DetectChanges
  - name: changedModulesRef
    type: string

stages:
- stage: ${{ parameters.moduleName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: and(always(), contains(${{ parameters.changedModulesRef }}, '${{ parameters.moduleName }}'))
  jobs:
  - job: Deploy${{ parameters.moduleName }}
    steps:
    - script: echo "Running ${{ parameters.moduleName }} module deployment"
      displayName: "Deploy ${{ parameters.moduleName }} Module"

  # - template: jobs/ado-publish-job.yml@templates
  #   parameters:
  #     targetPath: '${{ parameters.moduleName }}'
  #     artifactName: '${{ parameters.moduleName }}'

  # - template: jobs/terraform-plan.yml@templates
  #   parameters:
  #     environmentName: 'dev'
  #     TF_TOKEN: $(TF_TOKEN)
  #     terraformDirectory: '${{ parameters.moduleName }}'
